version: '3'

networks:
  my-network:
    driver: bridge

services:
  svc-account:
    build: 
      context: ./account
      # dockerfile: ./Dockerfile
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=accounts
    networks:
      - my-network
    ports:
      - 8080:8080

  database:
    image: postgres:12.3-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=accounts
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
    networks:
      - my-network
    ports:
      - 5432:5432
