version: '3'

networks:
  my-network:
    driver: bridge

services:
  svc-account:
    build: 
      context: ./account
      # dockerfile: ./Dockerfile
    depends_on:
      - database
    environment:
      - ES_HOST=database
      - ES_NAME=accounts
      - API_PORT=8000
    networks:
      - my-network
    ports:
      - 8000:8000

  svc-poller:
    build: 
      context: ./poller
      # dockerfile: ./Dockerfile
    depends_on:
      - database
      - nats
    environment:
      - ES_HOST=database
      - ES_NAME=accounts
      - NATS_ADDRESS=nats:4222
      - TOPIC=accounts
    networks:
      - my-network
    ports:
      - 3000:3000

  svc-balance:
    build: 
      context: ./balance
      # dockerfile: ./Dockerfile
    depends_on:
      - nats
      - elastic
    environment:
      - NATS_ADDRESS=nats:4222
      - TOPIC=accounts
      - REDIS_ADDRESSES=redis:6379
      - ES_ADDRESS=svc-poller:3000
      - ELASTIC_ADDRESSES=http://localhost:9200
    networks:
      - my-network
    ports:
      - 8030:8030

  database:
    image: postgres:12.3-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=accounts
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
    networks:
      - my-network
    ports:
      - 5432:5432

  nats:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - my-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    depends_on:
      - elastic
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - my-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my-network

volumes:
  data01:
    driver: local
