version: '3.4'

networks:
  my-network:
    driver: bridge

services:
  svc-account:
    build: 
      context: ../account
    depends_on:
      - m1
      - m2
      - mongo-seed
      - nats
      - consul
    environment:
      - ES_URL=mongodb://m1,m2/accounts?replicaSet=rs0
      - ES_NAME=accounts
      - DB_MIGRATIONS_URL=file:///app/migrations/
      - API_PORT=8000
      - NATS_URL=nats://nats:4222
      - TOPIC=accounts
      - CONSUL_URL=consul:8500
      - PARTITION_SLOTS=1-2,3-4 # 4 partitions spread through 2 workers, 2 partitions each
      - PARTITION=4
    networks:
      - my-network
    ports:
      - 8000:8000
      - 3000:3000

  # https://blog.lysender.com/2019/08/mongodb-replicaset-on-docker-environment/
  m1:
    image: mongo:latest
    command: --replSet rs0 --bind_ip_all
    environment:
      MONGO_INITDB_DATABASE: accounts
    ports:
      - "27017:27017"
    networks:
      - my-network
  m2:
    image: mongo:latest
    command: --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    networks:
      - my-network
    depends_on:
      - m1
  mongo-seed:
    build: ./mongo-seed
    networks:
      - my-network
    depends_on:
      - m1
      - m2

  nats:
    image: nats-streaming
    networks:
      - my-network
    ports:
      - "4222:4222"
      - "8222:8222"

  consul:
    image: bitnami/consul:1.9.3
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    networks:
      - my-network

  svc-balance:
    build: 
      context: ../
      dockerfile: ./balance/Dockerfile
    depends_on:
      - nats
      - elastic
      - consul
    environment:
      - NATS_URL=nats://nats:4222
      - TOPIC=accounts
      - CONSUL_URL=consul:8500
      - ES_ADDRESS=svc-account:3000
      - ELASTIC_URL=http://elastic:9200
      - PARTITIONS=4
    networks:
      - my-network
    ports:
      - 8030:8030

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - my-network
